### ISSUE TITLE
Overshadowing error introduced with 0.5.0

### ISSUE THREAD

**Issue by Olical** [bakpakin/Fennel#322]
Hi there! Thanks for working on Fennel, it's wonderful and I use it so much :tada:

I was trying to update [Aniseed](https://github.com/Olical/aniseed) to 0.5.0 but I'm getting compilation errors that I just don't understand:

```
for f in aniseed/compile aniseed/core aniseed/dotfiles aniseed/eval aniseed/fennel aniseed/fs aniseed/nvim aniseed/nvim/util aniseed/string aniseed/test aniseed/view; do \
	mkdir -p lua/$(dirname $f); \
	deps/Fennel/fennel scripts/internal/compile.fnl fnl/$f.fnl > lua/$f.lua; \
done
Compile error in src/fennel/macros.fnl:4
  local -> was overshadowed by a special form or macro

* Try renaming local ->.
Compile error in src/fennel/macros.fnl:4
  local -> was overshadowed by a special form or macro

* Try renaming local ->.

...
```

I compile each of my `.fnl` files to `.lua` ahead of time using this little script:

```fnl
(local fennel (require :deps/Fennel/fennel))

(set fennel.path (.. fennel.path ";fnl/?.fnl"))

(fn read-file [path]
  (let [file (io.open path "rb")
        content (file:read "*a")]
    (file:close)
    content))

(fn compile [content opts]
  (xpcall
    (fn []
      (fennel.compileString
        (.. "(require-macros :aniseed.macros)\n" content)
        opts))
    fennel.traceback))

(let [filename (. arg 1)
      (_ok? result) (-> filename
                        (read-file)
                        (compile {:filename filename}))]
  (print result))
```

This was all working fine with 0.4.2 but 0.5.0 doesn't seem to like it. I can't see anything in the changelog or the commits that gives me more of an idea, so I wonder if there's an issue? Or am I just doing something really dumb?

I would _guess_ it's because of some interplay between Fennel's macros and my own which are prepended to every file with `(.. "(require-macros :aniseed.macros)\n" content)`.

Thanks a lot!

**Comment by technomancy** [comment]
Hm; hard to say without more context; can you provide a minimal self-contained example of the problem? It looks like something is interfering with the compilation of Fennel's own built-in macros. The built-in macros got moved to a separate module instead of being an inline string embedded in the Lua code in 0.5.0; that's the only relevant change I can think of.

In general string concatenation with the code is not a great idea and is likely to cause unexpected problems and should be avoided.

**Comment by Olical** [comment]
Yep sure thing, sorry for dumping vague code on you :sweat_smile: I'll try to get a minimal repro.

Do you have any tips for how I could nicely inject a bunch of macros into my compilation? I've written a Clojure like module system which avoids having to return a table from your file. You just declare a `(module ...)` like a Clojure `(ns ...)` form with requires inside it then use `(def...)` macros to export things.

This is to facilitate namespace-ish interactive evaluation in the buffer while maintaining the correct context. So it has to be macros and I want it to be included everywhere. I'm wondering if there's a hook in the compiler that would work better for this sort of thing?

**Comment by technomancy** [comment]
> Do you have any tips for how I could nicely inject a bunch of macros into my compilation?

Well, one of the design goals with Fennel is that it should be very
obvious thru static analysis where every single identifier comes from,
leaning heavily on lexical scope for everything. This is a fundamental
tenet that informs the design thruout in order to maximize readability
and clarity.

For example, the early `require-macros` form is considered deprecated
specifically because it breaks this; the `import-macros` form does a
much better job of conveying at a glance where things come from. Nothing
should come from nowhere.

So what you're asking for goes against a pretty core design goal.

> I'm wondering if there's a hook in the compiler that would work better for this sort of thing?

That said, we are planning to add first-class plugins to the compiler to
facilitate major changes like this. There's a horribly-outdated sketch
of this on the "plugins" branch and some ideas on the wiki here:

https://github.com/bakpakin/Fennel/wiki/Plugins

So this might be a good use case to consider for the plugin system. Once
the dust settles around the self-hosting changes, I hope to be able to
pick back up on the plugin work.

> This is to facilitate namespace-ish interactive evaluation in the
> buffer while maintaining the correct context.

In the Lua runtime the chunk is the smallest viable unit of evaluation,
and lexical scope does not cross chunk boundaries. We fake it in the
repl but it's an inexact science. It's much more straightforward and
reliable to reload on a module-by-module basis (a la `lume.hotswap` or
fennel-mode's `fennel-reload` command) rather than arbitrary lines
within a buffer.

**Comment by Olical** [comment]
Ah okay, got it, I understand and agree with the direction of "make everything lexical". I still frown upon `:refer :all` when I see it in Clojure codebases. This is kind of a one off thing for my project that ends up re-flavouring (sweetening?) Fennel slightly, so it's not used in a general sense, it's just this one concept of modules that I introduce.

I kinda like the simplicity of doing it all the Lua way, but I wanted `(defonce ...)` for stateful things, re-evaluation of single functions and the ability to evaluate a block of code that referenced a required module. It works _really_ well and fits my mental model of interactive Clojure development. Definitely not a general thing, but it works well in my context of interactive evaluation tooling.

A compiler plugin might be a good thing for the future, I do have people that are interested in my module macros outside of my tooling, they just want the macros, I guess there's a niche of people who don't like the Lua way and want like 5% more magic to their module definitions. I certainly prefer it.

**Comment by technomancy** [comment]
> I kinda like the simplicity of doing it all the Lua way, but I wanted (defonce ...) for stateful things

I used to try to do stuff like this by storing stateful tables off in a global so they would survive reloads, but then I realized it is much cleaner to make the stateful table a module of its own, and only reload that when you actually *wanted* the statefulness wiped. That lets you isolate out the statefulness and keep the rest of the module cleaner.

> I do have people that are interested in my module macros outside of my tooling, they just want the macros

I've also heard from a couple people that they want the vim tooling *without* the replacement module system, so separating these two into distinct libraries would be a good idea.

**Comment by technomancy** [comment]
Hey, is there a repro case for this issue? If it's not actionable I'd rather close it on out; thanks.

**Comment by Olical** [comment]
I worked out what my issue was! I was running some Fennel from the command line like so:

```bash
deps/Fennel/fennel scripts/internal/compile.fnl fnl/$f.fnl > lua/$f.lua
```

Which in turn tried to `(require :deps/Fennel/fennel)`, so Fennel loaded twice and the core macros conflicted kinda! Now I'm just using `(require :fennel)` and everything's great.
